"""tests/contract/test_no_legacy_deft_run.py -- contract-string regression (#992 PR1).

Asserts the v0.27 install-layout flip ``deft/run`` -> ``.deft/core/run`` left
no in-scope occurrences of the legacy substring outside the documented
exclusion set. Owned by acceptance criterion ``992-ac-1-pr1-contract-strings``
on the active scope vBRIEF
``vbrief/active/2026-05-10-992-adopt-deftcore-as-canonical-install-layout-ship-relocator-an.vbrief.json``.

Dual-state proof
----------------

This test was authored as part of #992 PR1; by construction it MUST:

- **Fail on master before the PR1 commits land.** Master carries ``deft/run``
  references in every contract surface the AC enumerates (``README.md``,
  ``UPGRADING.md``, ``main.md``, ``templates/agents-entry.md``,
  ``docs/**``, ``skills/deft-directive-setup/SKILL.md``, ...). Running this
  module against master produces a non-empty hit list and the assertion
  fails -- intentional regression evidence.
- **Pass after the PR1 string-swap commits land.** Every in-scope file has
  been flipped to ``.deft/core/run``; the only ``deft/run`` references that
  remain are in the explicitly excluded set documented below (history,
  legacy redirect stubs, must-not-touch, auto-generated, scratch session
  logs, and the CLI surface that is intentionally docs-only-out-of-scope
  per the orchestrator's PR1 envelope).

Exclusion taxonomy
------------------

The acceptance-criterion text in items[0] mandates four exclusions:

1. ``history/archive/**`` -- archived design docs and historical artefacts.
2. ``vbrief/completed/**`` -- closed scope vBRIEFs are historical.
3. ``CHANGELOG.md`` -- historical entries reference the pre-flip surface.
4. ``meta/lessons.md`` -- historical pattern records.

Plus the eight legacy v0.19 -> v0.20 redirect stubs at
``skills/deft-{sync,setup,build,review-cycle,roadmap-refresh,swarm,pre-pr,interview}/SKILL.md``
which intentionally retain the pre-flip path so stale ``AGENTS.md``
references continue to resolve into the deprecation-redirect contract
documented in ``tests/content/test_deprecated_skill_redirects.py``.

Beyond the AC, this test also excludes the following surfaces because
they are either forbidden-to-edit in PR1 scope, auto-generated, working
copies of historical material, or explicitly carved out by the
orchestrator as docs-only-out-of-scope for PR1 (see the ``Scope deviation
notes`` block in the PR1 PR body):

- ``UPGRADING.md`` (canonical migration documentation -- by definition
  references BOTH the legacy ``deft/run`` path AND the canonical
  ``.deft/core/run`` path so consumers know what they are migrating FROM
  and TO. The #1015 F1 "Manual edits required after relocate (above-marker
  prose)" subsection explicitly enumerates the legacy occurrences
  consumers must update by hand; removing the literal token would break
  the doc's operator-actionable usefulness).

- ``vbrief/PROJECT-DEFINITION.vbrief.json`` (must-not-touch per the active
  vBRIEF's ``files_must_not_touch`` list; regenerated via ``task project:render``).
- ``vbrief/schemas/**`` (frozen schemas; out of scope).
- ``vbrief/active/**`` / ``vbrief/pending/**`` / ``vbrief/proposed/**`` /
  ``vbrief/cancelled/**`` (lifecycle vBRIEFs; the active #992 vBRIEF
  describes the flip in narrative form via the literal substring).
- ``ROADMAP.md`` (regenerated at release time only; must-not-touch).
- ``SPECIFICATION.md`` (auto-generated by ``task spec:render`` from
  ``vbrief/specification.vbrief.json`` plus historical narratives in
  ``vbrief/completed/**``; the rendered output mirrors the historical
  source content).
- ``history/**`` broader than ``history/archive/**`` (e.g. ``history/plan-*``,
  ``history/implementation-*`` are also historical artefacts).
- ``session.txt`` / ``session2.txt`` (developer scratch session logs from
  pre-v0.20 work; tracked but historical).
- ``run.py`` / ``run.bat`` (Python CLI siblings; legacy thin wrappers
  around ``run`` retained for backward compatibility -- contract-string
  flip on these is tracked as a separate follow-up because they live
  outside the canonical CLI entry point and have low blast radius). The
  primary ``run`` CLI script itself is NO LONGER excluded -- it was
  flipped in PR4 alongside ``tasks/framework.yml`` and
  ``events/registry.json``.
- ``cmd/deft-install/**`` (Go installer; functional code surface,
  follow-up).
- ``scripts/relocate.py`` / ``scripts/_relocate_states.py`` (PR2
  relocator; the `advise_external_hardcodes()` function intentionally
  searches consumer files OUTSIDE ``.deft/core/`` for ``deft/run``
  references and prints findings to help operators manually fix
  external hardcodes per the ADVISORY-NOT-AUTOFIX-FOR-EXTERNAL-HARDCODES
  DesignChoice on the active vBRIEF. The literal token lives in the
  relocator code as a search constant, function default arg, log
  message format string, and module docstring -- removing it would
  break the advisory feature). The relocator's own framework deposit
  is ``.deft/core/run``; the legacy-token search is for consumer-side
  detection only.
- ``tests/**`` (test files document both the legacy and canonical
  contract tokens by necessity -- they pin the redirect-stub contract,
  the canonical-vs-legacy split documented in `test_main_md_preamble.py`,
  and prose docstrings explaining the contract surface; tests are
  infrastructure rather than user-visible contract surfaces, so the
  regression scope properly stops at production source / docs).

Refs
----

- Active scope vBRIEF (filename split for line-length compliance):
  ``vbrief/active/2026-05-10-992-adopt-deftcore-as-canonical-
  install-layout-ship-relocator-an.vbrief.json``
- Parent issue: https://github.com/deftai/directive/issues/992
- Redirect stub list owner:
  ``tests/content/test_deprecated_skill_redirects.py``
"""

from __future__ import annotations

import subprocess
from pathlib import Path

import pytest

_REPO_ROOT = Path(__file__).resolve().parents[2]

# The literal substring being asserted absent. Tracked as a top-level
# constant so a future maintainer can search for the canonical token
# without needing to re-derive it from prose.
_LEGACY_TOKEN = "deft/run"

# Directory-prefix exclusions. A tracked file path is excluded if it
# starts with any of these prefixes (forward-slash form, matched against
# `git ls-files` output which is always forward-slash on Windows too).
_EXCLUDED_DIR_PREFIXES = (
    # AC-mandated
    "history/archive/",
    "vbrief/completed/",
    # Beyond-AC scope deviations (documented in module docstring above)
    "history/",                  # broader: plan-* / implementation-* / archive/**
    "vbrief/active/",
    "vbrief/pending/",
    "vbrief/proposed/",
    "vbrief/cancelled/",
    "vbrief/schemas/",
    "cmd/deft-install/",
    # Tests document contract tokens (legacy + canonical) by necessity --
    # they pin the redirect-stub gate-instruction split, document the
    # canonical-vs-legacy contract in prose, and exercise both surfaces
    # via fixtures. Tests are infrastructure, not user-visible contract
    # surfaces; regression scope stops at production source / docs.
    "tests/",
)

# Exact-path exclusions (forward-slash form, repo-root-relative).
_EXCLUDED_EXACT_PATHS = frozenset(
    {
        # AC-mandated
        "CHANGELOG.md",
        "meta/lessons.md",
        # Beyond-AC scope deviations (documented in module docstring above)
        "vbrief/PROJECT-DEFINITION.vbrief.json",
        "ROADMAP.md",
        "SPECIFICATION.md",
        "session.txt",
        "session2.txt",
        # PR4 (#992 PR4): `run`, `tasks/framework.yml`, and
        # `events/registry.json` were flipped to `.deft/core/run`; they are
        # NO LONGER excluded. The CLI sibling wrappers below remain excluded
        # as a low-blast-radius follow-up.
        "run.py",
        "run.bat",
        # PR2 (#992 PR2): relocator advisory-grep retains `deft/run` as a
        # search constant for consumer-side hardcode detection. See module
        # docstring `Beyond-AC` block for the rationale.
        "scripts/relocate.py",
        "scripts/_relocate_states.py",
        # #1015 F1: UPGRADING.md is the canonical migration docs surface and
        # MUST reference both the legacy `deft/run` and canonical
        # `.deft/core/run` paths so consumers know what to migrate FROM
        # and TO. The F1 "Manual edits required after relocate" subsection
        # is the operator's worklist; the literal token is load-bearing.
        "UPGRADING.md",
        # #992 PR5 (rc1 dogfood evidence): the smoke doc verbatim-quotes
        # the relocator's `advise_external_hardcodes()` advisory stdout
        # captured during a real dogfood run against `deftai/postmortem`.
        # That stdout legitimately contains the `deft/run` substring -- it
        # is the relocator REPORTING what it found in the consumer's
        # pre-v0.27 AGENTS.md `## Commands` block, which is itself the
        # operator-actionable signal the F1 follow-up was designed to
        # surface. Rewriting the doc to obfuscate the substring would
        # silently break the advisory output's evidentiary value. Mirrors
        # the `meta/lessons.md` carve-out shape (historical content that
        # quotes pre-flip surfaces verbatim).
        "docs/smoke-2026-05-10-v0.27.1-relocator-dogfood.md",
    }
)

# The eight legacy v0.19 -> v0.20 redirect-stub paths. These intentionally
# retain ``deft/run`` references so stale ``AGENTS.md`` references still
# resolve into the deprecation-redirect contract (#411). The list mirrors
# ``tests/content/test_deprecated_skill_redirects.py::_REDIRECT_STUBS`` --
# any addition there MUST be reflected here as well.
_LEGACY_REDIRECT_STUB_PATHS = frozenset(
    {
        f"skills/{name}/SKILL.md"
        for name in (
            "deft-sync",
            "deft-setup",
            "deft-build",
            "deft-review-cycle",
            "deft-roadmap-refresh",
            "deft-swarm",
            "deft-pre-pr",
            "deft-interview",
        )
    }
)


def _is_excluded(rel_path: str) -> bool:
    """Return True iff ``rel_path`` (forward-slash, repo-root-relative) is excluded."""
    if rel_path in _EXCLUDED_EXACT_PATHS:
        return True
    if rel_path in _LEGACY_REDIRECT_STUB_PATHS:
        return True
    return any(rel_path.startswith(prefix) for prefix in _EXCLUDED_DIR_PREFIXES)


def _tracked_files() -> list[str]:
    """Return the list of repo-tracked files via ``git ls-files``.

    Forward-slash separators on every platform (``git ls-files`` output is
    POSIX-style on Windows too). Falls back to a recursive directory walk
    only if ``git`` is unreachable, which would itself be a CI failure
    surface but lets the test produce a coherent error rather than a stack
    trace from ``subprocess``.
    """
    try:
        result = subprocess.run(
            ["git", "ls-files"],
            cwd=_REPO_ROOT,
            check=True,
            capture_output=True,
            text=True,
            encoding="utf-8",
        )
    except (subprocess.SubprocessError, FileNotFoundError) as exc:
        pytest.fail(
            f"Could not enumerate tracked files via `git ls-files`: {exc!r}. "
            "The contract regression cannot run without VCS metadata."
        )
    return [
        line.strip()
        for line in result.stdout.splitlines()
        if line.strip()
    ]


def _scan_legacy_token() -> list[tuple[str, int, str]]:
    """Return ``[(path, line_number, line_text)]`` for every in-scope hit."""
    hits: list[tuple[str, int, str]] = []
    for rel_path in _tracked_files():
        if _is_excluded(rel_path):
            continue
        full = _REPO_ROOT / rel_path
        if not full.is_file():
            continue
        try:
            text = full.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            # Binary or unreadable -- not a contract-string surface.
            continue
        if _LEGACY_TOKEN not in text:
            continue
        for idx, line in enumerate(text.splitlines(), start=1):
            if _LEGACY_TOKEN in line:
                hits.append((rel_path, idx, line.rstrip()))
    return hits


# ---------------------------------------------------------------------------
# Contract assertions
# ---------------------------------------------------------------------------


def test_no_legacy_deft_run_substring_in_scope() -> None:
    """No in-scope file may contain the legacy ``deft/run`` substring (#992 PR1).

    The exclusion taxonomy is documented in this module's docstring. A
    failure here means either (a) a contract surface was missed during the
    PR1 string-swap, or (b) a new file was added to the repo that
    introduces a fresh ``deft/run`` reference outside the redirect-stub
    contract. Either case must be addressed before merge.
    """
    hits = _scan_legacy_token()
    assert not hits, (
        "Found in-scope `deft/run` references after the #992 PR1 contract "
        "flip; expected zero. Either flip the remaining occurrences to "
        "`.deft/core/run` or, if the file is intentionally out of scope, "
        "extend the exclusion set in this test (and document the rationale "
        "in the module docstring + PR1 scope deviation notes).\n"
        + "\n".join(f"  {p}:{n}: {text}" for p, n, text in hits)
    )


def test_gate_preamble_redirect_stubs_retain_legacy_token() -> None:
    """Stubs that carry the DEFT-PREAMBLE-V1 gate instruction MUST keep ``deft/run``.

    Two of the eight v0.19 -> v0.20 redirect stubs (`skills/deft-setup/SKILL.md`
    and `skills/deft-build/SKILL.md`) carry the `<!-- DEFT-PREAMBLE-V1 -->`
    line-1 gate-instruction block (cross-tested by
    ``tests/content/test_main_md_preamble.py`` against the canonical-vs-legacy
    split documented there) -- those two MUST retain the pre-flip
    ``deft/run`` token so v0.19 stale-AGENTS.md references still resolve
    through the gate. The other six redirect stubs are simple sentinel-only
    redirect bodies pointing at ``deft/QUICK-START.md`` and never carried
    the gate-instruction surface; their redirect contract is covered
    independently by ``tests/content/test_deprecated_skill_redirects.py``.
    """
    gate_carrying_stubs = (
        "skills/deft-setup/SKILL.md",
        "skills/deft-build/SKILL.md",
    )
    failures: list[str] = []
    for rel_path in gate_carrying_stubs:
        full = _REPO_ROOT / rel_path
        if not full.is_file():
            failures.append(f"{rel_path}: gate-carrying stub file missing")
            continue
        text = full.read_text(encoding="utf-8")
        if _LEGACY_TOKEN not in text:
            failures.append(
                f"{rel_path}: missing `deft/run` -- gate-instruction "
                f"redirect contract broken (#411 + #768)"
            )
    assert not failures, (
        "Gate-instruction-carrying redirect stubs MUST retain the legacy "
        "`deft/run` token (#411 v0.19 -> v0.20 bridge + #768 gate "
        "instruction):\n  " + "\n  ".join(failures)
    )


def test_canonical_token_present_in_documented_surfaces() -> None:
    """Spot-check that the canonical ``.deft/core/run`` token actually landed.

    Pinned against a small set of high-signal contract surfaces from the
    AC enumeration so a partial flip (e.g. only one of the two
    ``templates/agents-entry.md`` references swapped) fails this test
    independently of the broader ``test_no_legacy_deft_run_substring_in_scope``
    sweep. Picks one occurrence per surface; the broader sweep covers the
    full inventory.
    """
    canonical = ".deft/core/run"
    documented_surfaces = (
        "templates/agents-entry.md",
        "main.md",
        "README.md",
        "UPGRADING.md",
        "docs/ARCHITECTURE.md",
        "docs/BROWNFIELD.md",
        "skills/deft-directive-setup/SKILL.md",
    )
    failures: list[str] = []
    for rel_path in documented_surfaces:
        full = _REPO_ROOT / rel_path
        assert full.is_file(), f"Expected documented surface {rel_path} to exist"
        text = full.read_text(encoding="utf-8")
        if canonical not in text:
            failures.append(f"{rel_path}: missing `{canonical}`")
    assert not failures, (
        "AC-enumerated contract surfaces must carry the canonical "
        f"`{canonical}` token after #992 PR1:\n  " + "\n  ".join(failures)
    )
