"""test_machine_generated_banner.py -- Banner-contract regression (#572).

Parametrises over the four machine-managed file writers documented in
``conventions/machine-generated-banner.md`` and asserts each one emits
the canonical 4-line banner with the expected ``Purpose`` token.

Writers covered:
  1. ``scripts/spec_render.py``              -> ``SPECIFICATION.md``
  2. ``scripts/prd_render.py``               -> ``PRD.md``
  3. ``scripts/roadmap_render.py``           -> ``ROADMAP.md``
  4. ``scripts/migrate_vbrief.py::_deprecation_redirect()``
     -> post-migration ``SPECIFICATION.md`` / ``PROJECT.md`` stubs

Any future ``task *:render`` writer MUST be added to this parametrize
list; a writer not covered here is a convention drift away from #572.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import pytest

_REPO_ROOT = Path(__file__).resolve().parent.parent.parent

# Ensure ``scripts/`` is importable so we can invoke the writer functions
# directly rather than via subprocess (faster + exercises the same code
# paths that the CLI subprocess tests cover).
sys.path.insert(0, str(_REPO_ROOT / "scripts"))

# Registered ``Purpose:`` values -- MUST match
# ``conventions/machine-generated-banner.md``.
REGISTERED_PURPOSES = frozenset(
    {
        "rendered specification",
        "rendered PRD",
        "rendered roadmap",
        "deprecation redirect",
    }
)

# Canonical banner prefix (first line). All four writers MUST open with
# this literal prefix so downstream detectors have a stable token.
_BANNER_PREFIX = "<!-- AUTO-GENERATED by "


def _write_spec_fixture(tmp_path: Path) -> Path:
    """Write a minimal v0.6 specification.vbrief.json fixture to tmp_path."""
    spec = {
        "vBRIEFInfo": {"version": "0.6"},
        "plan": {
            "title": "Banner Contract Test Project",
            "status": "approved",
            "narratives": {
                "Overview": "Fixture for the machine-generated banner contract test.",
            },
            "items": [],
        },
    }
    spec_path = tmp_path / "vbrief" / "specification.vbrief.json"
    spec_path.parent.mkdir(parents=True, exist_ok=True)
    spec_path.write_text(json.dumps(spec, indent=2), encoding="utf-8")
    return spec_path


def _write_pending_fixture(tmp_path: Path) -> Path:
    """Write a minimal v0.6 scope vBRIEF to vbrief/pending/ so roadmap
    render has something to emit."""
    pending = tmp_path / "vbrief" / "pending"
    pending.mkdir(parents=True, exist_ok=True)
    scope = {
        "vBRIEFInfo": {"version": "0.6"},
        "plan": {
            "title": "Banner Contract Scope",
            "status": "pending",
            "items": [],
            "references": [],
        },
    }
    (pending / "2026-04-22-banner-contract-scope.vbrief.json").write_text(
        json.dumps(scope, indent=2), encoding="utf-8"
    )
    return pending


def _assert_canonical_banner(
    content: str,
    *,
    purpose: str,
    generator: str,
    source: str,
    regenerate: str,
) -> None:
    """Assert ``content`` opens with the canonical 4-line banner.

    All four lines (``AUTO-GENERATED`` / ``Purpose`` / ``Source of truth``
    / ``Regenerate with``) must be populated, in order, as the first four
    lines of the file. Placeholders like ``{...}`` are explicitly rejected.
    """
    lines = content.splitlines()
    assert len(lines) >= 4, (
        f"expected at least four banner lines, got {len(lines)}:\n{content[:200]}"
    )
    # Line 1: AUTO-GENERATED + generator
    assert lines[0].startswith(_BANNER_PREFIX), (
        f"first line must start with {_BANNER_PREFIX!r}, got {lines[0]!r}"
    )
    assert generator in lines[0], (
        f"first line must name the generator {generator!r}, got {lines[0]!r}"
    )
    assert "DO NOT EDIT MANUALLY" in lines[0], (
        "first line must carry the 'DO NOT EDIT MANUALLY' clause per "
        "conventions/machine-generated-banner.md"
    )
    # Line 2: Purpose
    assert lines[1] == f"<!-- Purpose: {purpose} -->", (
        f"line 2 must be exactly '<!-- Purpose: {purpose} -->', got {lines[1]!r}"
    )
    assert purpose in REGISTERED_PURPOSES, (
        f"purpose {purpose!r} must be one of the registered values "
        f"{sorted(REGISTERED_PURPOSES)}"
    )
    # Line 3: Source of truth
    assert lines[2] == f"<!-- Source of truth: {source} -->", (
        f"line 3 must be exactly '<!-- Source of truth: {source} -->', "
        f"got {lines[2]!r}"
    )
    # Line 4: Regenerate with
    assert lines[3] == f"<!-- Regenerate with: {regenerate} -->", (
        f"line 4 must be exactly '<!-- Regenerate with: {regenerate} -->', "
        f"got {lines[3]!r}"
    )
    # No placeholders leaked through.
    for idx in range(4):
        assert "{" not in lines[idx] and "}" not in lines[idx], (
            f"line {idx + 1} still contains an unpopulated placeholder: "
            f"{lines[idx]!r}"
        )


def _render_spec(tmp_path: Path) -> str:
    """Invoke ``scripts/spec_render.render_spec`` on a fixture and return
    the rendered SPECIFICATION.md content."""
    import spec_render  # type: ignore[import-not-found]

    spec_path = _write_spec_fixture(tmp_path)
    out_path = tmp_path / "SPECIFICATION.md"
    ok, _msg = spec_render.render_spec(
        str(spec_path), str(out_path), include_scopes=False
    )
    assert ok, f"spec_render.render_spec failed: {_msg}"
    return out_path.read_text(encoding="utf-8")


def _render_prd(tmp_path: Path) -> str:
    """Invoke ``scripts/prd_render.render_prd`` on a fixture and return
    the rendered PRD.md content."""
    import prd_render  # type: ignore[import-not-found]

    spec_path = _write_spec_fixture(tmp_path)
    out_path = tmp_path / "PRD.md"
    prd_render.render_prd(spec_path, out_path)
    return out_path.read_text(encoding="utf-8")


def _render_roadmap(tmp_path: Path) -> str:
    """Invoke ``scripts/roadmap_render.render_roadmap`` on a fixture and
    return the rendered ROADMAP.md content."""
    import roadmap_render  # type: ignore[import-not-found]

    pending = _write_pending_fixture(tmp_path)
    out_path = tmp_path / "ROADMAP.md"
    ok, _msg = roadmap_render.render_roadmap(str(pending), str(out_path))
    assert ok, f"roadmap_render.render_roadmap failed: {_msg}"
    return out_path.read_text(encoding="utf-8")


def _render_deprecation_redirect(tmp_path: Path) -> str:
    """Invoke ``migrate_vbrief._deprecation_redirect`` directly and return
    the generated redirect content."""
    import migrate_vbrief  # type: ignore[import-not-found]

    return migrate_vbrief._deprecation_redirect(
        "SPECIFICATION.md",
        "vbrief/PROJECT-DEFINITION.vbrief.json",
        "Fixture scope note for banner contract regression test.",
    )


# Parametrize over the four writers. Each entry is
# (writer_id, render_callable, purpose, generator, source, regenerate).
BANNER_CASES = [
    pytest.param(
        "spec_render",
        _render_spec,
        "rendered specification",
        "task spec:render",
        "vbrief/specification.vbrief.json",
        "task spec:render",
        id="spec_render",
    ),
    pytest.param(
        "prd_render",
        _render_prd,
        "rendered PRD",
        "task prd:render",
        "vbrief/specification.vbrief.json",
        "task prd:render",
        id="prd_render",
    ),
    pytest.param(
        "roadmap_render",
        _render_roadmap,
        "rendered roadmap",
        "task roadmap:render",
        "vbrief/pending/ (scope vBRIEFs)",
        "task roadmap:render",
        id="roadmap_render",
    ),
    pytest.param(
        "migrate_vbrief_deprecation_redirect",
        _render_deprecation_redirect,
        "deprecation redirect",
        "task migrate:vbrief",
        "n/a",
        "task migrate:vbrief",
        id="migrate_vbrief_deprecation_redirect",
    ),
]


@pytest.mark.parametrize(
    "writer_id,render_fn,purpose,generator,source,regenerate",
    BANNER_CASES,
)
def test_writer_emits_canonical_banner(
    writer_id: str,
    render_fn,
    purpose: str,
    generator: str,
    source: str,
    regenerate: str,
    tmp_path: Path,
) -> None:
    """Every machine-managed file writer emits the canonical 4-line banner
    with all fields populated (``conventions/machine-generated-banner.md``,
    #572)."""
    content = render_fn(tmp_path)
    _assert_canonical_banner(
        content,
        purpose=purpose,
        generator=generator,
        source=source,
        regenerate=regenerate,
    )


def test_registered_purposes_match_convention_doc() -> None:
    """The ``Purpose`` registry in the convention doc must match the
    ``REGISTERED_PURPOSES`` set used by this test."""
    doc_path = _REPO_ROOT / "conventions" / "machine-generated-banner.md"
    assert doc_path.is_file(), (
        "conventions/machine-generated-banner.md must exist (#572 AC 1)"
    )
    doc = doc_path.read_text(encoding="utf-8")
    for purpose in REGISTERED_PURPOSES:
        assert f"`{purpose}`" in doc, (
            f"Purpose {purpose!r} not documented in conventions/"
            f"machine-generated-banner.md (#572 AC 1)"
        )


def test_migrator_auto_markers_include_canonical_banner_tokens() -> None:
    """``_SPEC_AUTO_MARKERS`` and ``_PROJECT_AUTO_MARKERS`` must include
    the canonical-banner tokens so ``_is_user_customized()`` correctly
    classifies files carrying the new banner as machine-managed (#572 AC 3).
    """
    import migrate_vbrief  # type: ignore[import-not-found]

    for marker_tuple_name in ("_SPEC_AUTO_MARKERS", "_PROJECT_AUTO_MARKERS"):
        tup = getattr(migrate_vbrief, marker_tuple_name)
        assert "AUTO-GENERATED by" in tup, (
            f"{marker_tuple_name} must include 'AUTO-GENERATED by' "
            f"so files with the canonical banner are recognised (#572)"
        )
        # Greptile P2 on the PR review: the marker must be the FULL
        # ``<!-- Purpose:`` HTML-comment prefix, not the bare
        # ``Purpose:`` string, to avoid false positives from
        # hand-authored prose that mentions "Purpose: ...".
        assert "<!-- Purpose:" in tup, (
            f"{marker_tuple_name} must include the '<!-- Purpose:' "
            f"HTML-comment prefix (#572 AC 3, Greptile P2)"
        )
        assert "Purpose:" not in tup, (
            f"{marker_tuple_name} must NOT include the bare 'Purpose:' "
            f"token (would match hand-authored prose -- Greptile P2)"
        )


def test_setup_skill_detects_both_legacy_and_canonical_markers() -> None:
    """skills/deft-directive-setup/SKILL.md pre-cutover guard MUST accept
    both the legacy deprecation sentinel AND the canonical banner Purpose
    marker for one release cycle (#572 AC 3)."""
    skill = _REPO_ROOT / "skills" / "deft-directive-setup" / "SKILL.md"
    text = skill.read_text(encoding="utf-8")
    assert "<!-- deft:deprecated-redirect -->" in text, (
        "setup SKILL must still mention the legacy deprecated-redirect "
        "sentinel so consumers migrated under rc.1 / rc.2 are not "
        "re-flagged as pre-cutover"
    )
    assert "Purpose: deprecation redirect" in text, (
        "setup SKILL must also detect the current canonical-banner "
        "'Purpose: deprecation redirect' marker (#572 AC 3)"
    )
