#!/usr/bin/env bash
# init.sh — Bootstrap an autoresearch session from scratch.
#
# Reduces human setup to near-zero by:
#   - Creating the autoresearch branch (if on main/master)
#   - Initialising results/ and autoresearch.tsv
#   - Auto-detecting the training command from common project files
#   - Creating a research.env stub pre-filled with detected values
#   - Creating a program.md stub (copy of program-template.md)
#
# After running this, give the agent the all-in-one prompt from README.md.
# The agent will fill in what init.sh could not auto-detect.
#
# Usage:
#   ./scripts/init.sh [max_hours]

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
MAX_HOURS="${1:-2}"
ENV_FILE="$REPO_ROOT/research.env"
PROGRAM_FILE="$REPO_ROOT/program.md"
RESULTS_DIR="$REPO_ROOT/results"
RESULTS_TSV="$RESULTS_DIR/autoresearch.tsv"

cd "$REPO_ROOT"

echo ""
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║  AutoResearch — init                                          ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""

# ── 1. Create autoresearch branch ────────────────────────────────────────────
CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown")
BRANCH="autoresearch/$(date +%b%d | tr '[:upper:]' '[:lower:]')"

if [[ "$CURRENT_BRANCH" == "main" || "$CURRENT_BRANCH" == "master" ]]; then
    if git show-ref --verify --quiet "refs/heads/$BRANCH" 2>/dev/null; then
        echo "▶ Resuming branch: $BRANCH"
        git checkout "$BRANCH"
    else
        echo "▶ Creating branch: $BRANCH"
        git checkout -b "$BRANCH"
    fi
else
    echo "▶ Already on branch: $CURRENT_BRANCH (not switching)"
fi

# ── 2. Initialise results/ ────────────────────────────────────────────────────
mkdir -p "$RESULTS_DIR"
if [ ! -f "$RESULTS_TSV" ]; then
    printf "commit\tmetric\tstatus\tdescription\n" > "$RESULTS_TSV"
    echo "▶ Created $RESULTS_TSV"
else
    echo "▶ Results TSV already exists"
fi

# ── 3. Auto-detect training command ──────────────────────────────────────────
DETECTED_CMD=""
DETECTED_FROM=""

# Taskfile.yml — look for a task that contains "train" in name or cmd
if [ -f "$REPO_ROOT/Taskfile.yml" ] && command -v task &>/dev/null; then
    TASK_NAME=$(grep -E '^\s{2}train[^:]*:' "$REPO_ROOT/Taskfile.yml" \
                | head -1 | sed 's/:.*//' | tr -d ' ' || true)
    if [ -n "$TASK_NAME" ]; then
        DETECTED_CMD="task $TASK_NAME"
        DETECTED_FROM="Taskfile.yml (task: $TASK_NAME)"
    fi
fi

# Makefile
if [ -z "$DETECTED_CMD" ] && [ -f "$REPO_ROOT/Makefile" ]; then
    MAKE_TARGET=$(grep -E '^train[^:]*:' "$REPO_ROOT/Makefile" \
                  | head -1 | sed 's/:.*//' || true)
    if [ -n "$MAKE_TARGET" ]; then
        DETECTED_CMD="make $MAKE_TARGET"
        DETECTED_FROM="Makefile (target: $MAKE_TARGET)"
    fi
fi

# package.json
if [ -z "$DETECTED_CMD" ] && [ -f "$REPO_ROOT/package.json" ]; then
    if python3 -c "import json; d=json.load(open('package.json')); exit(0 if 'train' in d.get('scripts',{}) else 1)" 2>/dev/null; then
        DETECTED_CMD="npm run train"
        DETECTED_FROM="package.json (scripts.train)"
    fi
fi

# Common Python entry points
if [ -z "$DETECTED_CMD" ]; then
    for candidate in train.py training/train.py src/train.py main.py; do
        if [ -f "$REPO_ROOT/$candidate" ]; then
            DETECTED_CMD="python $candidate --seed 42"
            DETECTED_FROM="$candidate (detected file)"
            break
        fi
    done
fi

if [ -n "$DETECTED_CMD" ]; then
    echo "▶ Detected training command: $DETECTED_CMD  (from $DETECTED_FROM)"
else
    DETECTED_CMD="# TODO: fill in your training command"
    echo "⚠  Could not auto-detect training command — fill in TRAIN_CMD manually"
fi

# ── 4. Create research.env stub ───────────────────────────────────────────────
if [ -f "$ENV_FILE" ]; then
    echo "▶ research.env already exists — not overwriting"
else
    cat > "$ENV_FILE" << EOF
# research.env — AutoResearch configuration
# Generated by init.sh. Fill in the TODO fields before running the loop.

# ── Experiment command ────────────────────────────────────────────────────────
TRAIN_CMD="$DETECTED_CMD"

# ── Metric extraction ─────────────────────────────────────────────────────────
# Python regex with ONE capture group that extracts the metric from training output.
# Run your training command once and look for the final metric line, then set this.
METRIC_PATTERN="# TODO: e.g. \"Test F1=([0-9.]+)\""

# "higher" = bigger is better (F1, accuracy, AUC, R²)
# "lower"  = smaller is better (loss, perplexity, MSE)
METRIC_DIRECTION="higher"

# ── Baseline ──────────────────────────────────────────────────────────────────
# Run the training command once, record the metric, then set this.
BASELINE_METRIC="0.000"

# ── Editable files ────────────────────────────────────────────────────────────
# Space-separated. Only files controlling model arch, HPs, or config.
# NEVER include: evaluation logic, data/, seed flags, or metric extraction.
EDITABLE_FILES="# TODO: e.g. model.py train.py"

# ── Time budget and threshold ─────────────────────────────────────────────────
MAX_HOURS=$MAX_HOURS
MIN_DELTA=0.005
EOF
    echo "▶ Created research.env stub (fill in METRIC_PATTERN, BASELINE_METRIC, EDITABLE_FILES)"
fi

# ── 5. Create program.md stub ─────────────────────────────────────────────────
if [ -f "$PROGRAM_FILE" ]; then
    echo "▶ program.md already exists — not overwriting"
else
    if [ -f "$REPO_ROOT/program-template.md" ]; then
        cp "$REPO_ROOT/program-template.md" "$PROGRAM_FILE"
        echo "▶ Created program.md from template (fill in project-specific details)"
    else
        echo "⚠  program-template.md not found — create program.md manually"
    fi
fi

# ── Summary ───────────────────────────────────────────────────────────────────
echo ""
echo "════════════════════════════════════════════════════════════════"
echo "  Init complete. What still needs human/agent input:"
echo ""
if [ "$DETECTED_CMD" = "# TODO: fill in your training command" ]; then
    echo "  ☐ research.env: TRAIN_CMD  (could not auto-detect)"
else
    echo "  ✓ research.env: TRAIN_CMD  → $DETECTED_CMD"
fi
echo "  ☐ research.env: METRIC_PATTERN  (run training, grep for the metric line)"
echo "  ☐ research.env: BASELINE_METRIC (run training once, record the value)"
echo "  ☐ research.env: EDITABLE_FILES  (list files safe to modify)"
echo "  ☐ program.md:   fill in real experiments, values, and constraints"
echo ""
echo "  Tip: give the agent the all-in-one prompt from README.md §Agent Prompts."
echo "  It will complete the remaining setup and start the loop automatically."
echo "════════════════════════════════════════════════════════════════"
echo ""
