"""test_pack_migrate_swarm_spec.py -- in-process tests for the swarm-spec pack migration (#1637).

Covers (per the new-source test mandate):
- extract_title / extract_description: leading H1 + leading paragraph, with
  chrome (Legend, See-also, HTML comments) skipped and blockquote redirects
  yielding a readable description.
- migrate: parse -> source round-trip; one entry per swarm/*.md; the designated
  proof entry carries a body; stem-derived triggers.
- schema: the generated source validates against the swarm-spec-pack schema
  (lightweight in-test validator -- no jsonschema dependency).

All tests drive the module functions directly so coverage attributes to
pack_migrate_swarm_spec.py.
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

import pytest

_REPO_ROOT = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(_REPO_ROOT / "scripts"))

import pack_migrate_swarm_spec  # type: ignore[import-not-found]  # noqa: E402

_REAL_SOURCE = _REPO_ROOT / "packs" / "swarm-spec" / "swarm-spec-pack-0.1.json"
_REAL_SCHEMA = _REPO_ROOT / "vbrief" / "schemas" / "swarm-spec-pack.schema.json"
_PROOF_ENTRY = "swarm/swarm.md"

FIXTURE_SWARM_MD = """# Swarm Coordination Guidelines

Multi-agent coordination patterns for parallel software development across
isolated worktrees.

Legend (from RFC2119): !=MUST, ~=SHOULD.

**See also**: [other.md](./other.md)

---

## When to Use

- ~ Multiple independent stories.
"""

FIXTURE_NO_DESC_MD = """# Bare Spec

## Section

Body.
"""


def _build(tmp_path: Path, proof: str = "swarm/swarm.md") -> dict:
    sdir = tmp_path / "swarm"
    sdir.mkdir()
    (sdir / "swarm.md").write_text(FIXTURE_SWARM_MD, encoding="utf-8")
    return pack_migrate_swarm_spec.build_pack(sdir, proof_entry=proof)


# --- title / description extraction -----------------------------------------


def test_extract_title() -> None:
    assert (
        pack_migrate_swarm_spec.extract_title(FIXTURE_SWARM_MD)
        == "Swarm Coordination Guidelines"
    )
    assert pack_migrate_swarm_spec.extract_title("no heading") == ""


def test_extract_description_folds_paragraph_and_skips_chrome() -> None:
    desc = pack_migrate_swarm_spec.extract_description(FIXTURE_SWARM_MD)
    assert desc.startswith("Multi-agent coordination patterns")
    assert "Legend" not in desc
    assert "See also" not in desc


def test_extract_description_empty_when_only_sections() -> None:
    assert pack_migrate_swarm_spec.extract_description(FIXTURE_NO_DESC_MD) == ""


# --- migrate / build_pack ---------------------------------------------------


def test_build_pack_one_entry_per_doc(tmp_path: Path) -> None:
    pack = _build(tmp_path)
    ids = sorted(e["id"] for e in pack["entries"])
    assert ids == ["swarm"]
    swarm = next(e for e in pack["entries"] if e["id"] == "swarm")
    assert swarm["path"] == "swarm/swarm.md"
    assert swarm["title"] == "Swarm Coordination Guidelines"
    assert swarm["triggers"] == ["swarm"]


def test_build_pack_proof_carries_body(tmp_path: Path) -> None:
    pack = _build(tmp_path)
    bodied = [e for e in pack["entries"] if e["body"] is not None]
    assert len(bodied) == 1
    assert bodied[0]["id"] == "swarm"
    assert bodied[0]["body"].startswith("# Swarm Coordination Guidelines")


def test_migrate_writes_and_round_trips(tmp_path: Path) -> None:
    sdir = tmp_path / "swarm"
    sdir.mkdir()
    (sdir / "swarm.md").write_text(FIXTURE_SWARM_MD, encoding="utf-8")
    out = tmp_path / "out" / "swarm-spec-pack-0.1.json"
    pack = pack_migrate_swarm_spec.migrate(sdir, out, proof_entry="swarm/swarm.md")
    assert out.is_file()
    assert pack["pack"] == "swarm-spec-pack-0.1"
    assert pack["version"] == "0.1"
    assert json.loads(out.read_text(encoding="utf-8")) == pack


def test_strip_leading_banner_idempotent() -> None:
    body = "# Swarm Coordination Guidelines\n\nContent.\n"
    banner = (
        "<!-- AUTO-GENERATED by task packs:render -- DO NOT EDIT MANUALLY -->\n"
        "<!-- Purpose: rendered swarm spec -->\n"
    )
    bannered = banner + "\n" + body
    assert pack_migrate_swarm_spec.strip_leading_banner(bannered) == body
    assert pack_migrate_swarm_spec.strip_leading_banner(body) == body


def test_migrate_missing_dir_raises(tmp_path: Path) -> None:
    with pytest.raises(FileNotFoundError):
        pack_migrate_swarm_spec.migrate(
            tmp_path / "nope", tmp_path / "o.json", proof_entry="swarm/swarm.md"
        )


def test_migrate_no_entries_raises(tmp_path: Path) -> None:
    sdir = tmp_path / "swarm"
    sdir.mkdir()
    with pytest.raises(ValueError, match="no swarm-spec docs"):
        pack_migrate_swarm_spec.migrate(
            sdir, tmp_path / "o.json", proof_entry="swarm/swarm.md"
        )


def test_migrate_main_exit_codes(tmp_path: Path, capsys: pytest.CaptureFixture) -> None:
    sdir = tmp_path / "swarm"
    sdir.mkdir()
    (sdir / "swarm.md").write_text(FIXTURE_SWARM_MD, encoding="utf-8")
    out = tmp_path / "pack.json"
    rc = pack_migrate_swarm_spec.main(
        [
            "--swarm-dir", str(sdir),
            "--proof-entry", "swarm/swarm.md",
            "--out", str(out),
        ]
    )
    assert rc == 0
    assert "with body" in capsys.readouterr().out
    rc_missing = pack_migrate_swarm_spec.main(["--swarm-dir", str(tmp_path / "nope")])
    assert rc_missing == 1


# --- schema validation (lightweight) ----------------------------------------


def _validate_swarm_spec_source(pack: dict, schema: dict) -> list[str]:
    errors: list[str] = []
    props = schema["properties"]
    if pack.get("pack") != props["pack"]["const"]:
        errors.append("pack const mismatch")
    if pack.get("version") != props["version"]["const"]:
        errors.append("version const mismatch")
    if not isinstance(pack.get("entries"), list):
        errors.append("entries must be a list")
        return errors
    item_props = props["entries"]["items"]["properties"]
    required = props["entries"]["items"]["required"]
    id_re = re.compile(item_props["id"]["pattern"])
    path_re = re.compile(item_props["path"]["pattern"])
    for i, entry in enumerate(pack["entries"]):
        for key in required:
            if key not in entry:
                errors.append(f"entry {i} missing required key {key}")
        if not id_re.match(entry.get("id", "")):
            errors.append(f"entry {i} id pattern: {entry.get('id')!r}")
        if not path_re.match(entry.get("path", "")):
            errors.append(f"entry {i} path pattern: {entry.get('path')!r}")
        if not isinstance(entry.get("triggers"), list):
            errors.append(f"entry {i} triggers must be a list")
        body = entry.get("body")
        if body is not None and not isinstance(body, str):
            errors.append(f"entry {i} body must be str or null")
    return errors


def test_generated_source_validates_against_schema() -> None:
    pack = json.loads(_REAL_SOURCE.read_text(encoding="utf-8"))
    schema = json.loads(_REAL_SCHEMA.read_text(encoding="utf-8"))
    errors = _validate_swarm_spec_source(pack, schema)
    assert errors == [], f"schema validation errors: {errors}"


def test_real_pack_proof_body_present() -> None:
    pack = json.loads(_REAL_SOURCE.read_text(encoding="utf-8"))
    bodied = [e for e in pack["entries"] if e["body"] is not None]
    assert _PROOF_ENTRY in [e["path"] for e in bodied]


def test_schema_display_and_registry() -> None:
    schema = json.loads(_REAL_SCHEMA.read_text(encoding="utf-8"))
    assert schema["x-display"]["heading"] == "id"
    assert schema["x-display"]["body"] is None
    assert set(schema["x-sliceRegistry"]) == {"by-trigger", "list"}
    assert schema["x-sliceRegistry"]["by-trigger"]["filters"] == ["trigger"]
