"""test_pack_migrate_patterns.py -- in-process tests for the patterns pack migration (#1637).

Covers (per the new-source test mandate):
- extract_title / extract_description: leading H1 + leading paragraph, with
  chrome (Legend, See-also, HTML comments) skipped and blockquote redirects
  yielding a readable description.
- migrate: parse -> source round-trip; one entry per patterns/*.md; the
  designated proof pattern carries a body (others null); stem-derived triggers.
- schema: the generated source validates against the patterns-pack schema
  (lightweight in-test validator -- no jsonschema dependency).

All tests drive the module functions directly so coverage attributes to
pack_migrate_patterns.py.
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

import pytest

_REPO_ROOT = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(_REPO_ROOT / "scripts"))

import pack_migrate_patterns  # type: ignore[import-not-found]  # noqa: E402

_REAL_SOURCE = _REPO_ROOT / "packs" / "patterns" / "patterns-pack-0.1.json"
_REAL_SCHEMA = _REPO_ROOT / "vbrief" / "schemas" / "patterns-pack.schema.json"
_PROOF_PATTERN = "patterns/multi-agent.md"

FIXTURE_MULTI_AGENT_MD = """# Multi-agent identity separation pattern

This pattern lays out whose GitHub identity dispatched workers authenticate as,
why that should not be the maintainer's PAT, and how operators rotate it.

Legend (from RFC2119): !=MUST, ~=SHOULD.

**See also**: [other.md](./other.md)

---

## Why this matters

- ! Workers MUST authenticate as a distinct identity.
"""

FIXTURE_REDIRECT_MD = """# Legacy Pattern (Redirect)

> **This file is a legacy alias.** See multi-agent.md for the canonical pattern.
"""

FIXTURE_NO_DESC_MD = """# Bare Pattern

## Section

Body.
"""


def _build(tmp_path: Path, proof: str = "patterns/multi-agent.md") -> dict:
    pdir = tmp_path / "patterns"
    pdir.mkdir()
    (pdir / "multi-agent.md").write_text(FIXTURE_MULTI_AGENT_MD, encoding="utf-8")
    (pdir / "legacy.md").write_text(FIXTURE_REDIRECT_MD, encoding="utf-8")
    return pack_migrate_patterns.build_pack(pdir, proof_pattern=proof)


# --- title / description extraction -----------------------------------------


def test_extract_title() -> None:
    assert (
        pack_migrate_patterns.extract_title(FIXTURE_MULTI_AGENT_MD)
        == "Multi-agent identity separation pattern"
    )
    assert pack_migrate_patterns.extract_title("no heading") == ""


def test_extract_description_folds_paragraph_and_skips_chrome() -> None:
    desc = pack_migrate_patterns.extract_description(FIXTURE_MULTI_AGENT_MD)
    assert desc.startswith("This pattern lays out whose GitHub identity")
    # Legend / See-also chrome is NOT captured as the description.
    assert "Legend" not in desc
    assert "See also" not in desc


def test_extract_description_strips_blockquote_redirect() -> None:
    desc = pack_migrate_patterns.extract_description(FIXTURE_REDIRECT_MD)
    assert desc.startswith("**This file is a legacy alias.**")
    assert not desc.startswith(">")


def test_extract_description_empty_when_only_sections() -> None:
    assert pack_migrate_patterns.extract_description(FIXTURE_NO_DESC_MD) == ""


# --- migrate / build_pack ---------------------------------------------------


def test_build_pack_one_entry_per_doc(tmp_path: Path) -> None:
    pack = _build(tmp_path)
    ids = sorted(p["id"] for p in pack["patterns"])
    assert ids == ["legacy", "multi-agent"]
    ma = next(p for p in pack["patterns"] if p["id"] == "multi-agent")
    assert ma["path"] == "patterns/multi-agent.md"
    assert ma["title"] == "Multi-agent identity separation pattern"
    assert ma["triggers"] == ["multi-agent"]


def test_build_pack_proof_carries_body_others_null(tmp_path: Path) -> None:
    pack = _build(tmp_path)
    bodied = [p for p in pack["patterns"] if p["body"] is not None]
    assert len(bodied) == 1
    assert bodied[0]["id"] == "multi-agent"
    assert bodied[0]["body"].startswith("# Multi-agent identity separation pattern")


def test_migrate_writes_and_round_trips(tmp_path: Path) -> None:
    pdir = tmp_path / "patterns"
    pdir.mkdir()
    (pdir / "multi-agent.md").write_text(FIXTURE_MULTI_AGENT_MD, encoding="utf-8")
    out = tmp_path / "out" / "patterns-pack-0.1.json"
    pack = pack_migrate_patterns.migrate(
        pdir, out, proof_pattern="patterns/multi-agent.md"
    )
    assert out.is_file()
    assert pack["pack"] == "patterns-pack-0.1"
    assert pack["version"] == "0.1"
    assert json.loads(out.read_text(encoding="utf-8")) == pack


def test_strip_leading_banner_idempotent() -> None:
    body = "# Multi-agent identity separation pattern\n\nContent.\n"
    banner = (
        "<!-- AUTO-GENERATED by task packs:render -- DO NOT EDIT MANUALLY -->\n"
        "<!-- Purpose: rendered pattern -->\n"
    )
    bannered = banner + "\n" + body
    assert pack_migrate_patterns.strip_leading_banner(bannered) == body
    assert pack_migrate_patterns.strip_leading_banner(body) == body


def test_migrate_missing_dir_raises(tmp_path: Path) -> None:
    with pytest.raises(FileNotFoundError):
        pack_migrate_patterns.migrate(
            tmp_path / "nope", tmp_path / "o.json", proof_pattern="patterns/multi-agent.md"
        )


def test_migrate_no_patterns_raises(tmp_path: Path) -> None:
    pdir = tmp_path / "patterns"
    pdir.mkdir()
    with pytest.raises(ValueError, match="no patterns"):
        pack_migrate_patterns.migrate(
            pdir, tmp_path / "o.json", proof_pattern="patterns/multi-agent.md"
        )


def test_migrate_main_exit_codes(tmp_path: Path, capsys: pytest.CaptureFixture) -> None:
    pdir = tmp_path / "patterns"
    pdir.mkdir()
    (pdir / "multi-agent.md").write_text(FIXTURE_MULTI_AGENT_MD, encoding="utf-8")
    out = tmp_path / "pack.json"
    rc = pack_migrate_patterns.main(
        [
            "--patterns-dir", str(pdir),
            "--proof-pattern", "patterns/multi-agent.md",
            "--out", str(out),
        ]
    )
    assert rc == 0
    assert "with body" in capsys.readouterr().out
    rc_missing = pack_migrate_patterns.main(
        ["--patterns-dir", str(tmp_path / "nope")]
    )
    assert rc_missing == 1


# --- schema validation (lightweight) ----------------------------------------


def _validate_patterns_source(pack: dict, schema: dict) -> list[str]:
    errors: list[str] = []
    props = schema["properties"]
    if pack.get("pack") != props["pack"]["const"]:
        errors.append("pack const mismatch")
    if pack.get("version") != props["version"]["const"]:
        errors.append("version const mismatch")
    if not isinstance(pack.get("patterns"), list):
        errors.append("patterns must be a list")
        return errors
    item_props = props["patterns"]["items"]["properties"]
    required = props["patterns"]["items"]["required"]
    id_re = re.compile(item_props["id"]["pattern"])
    path_re = re.compile(item_props["path"]["pattern"])
    for i, entry in enumerate(pack["patterns"]):
        for key in required:
            if key not in entry:
                errors.append(f"entry {i} missing required key {key}")
        if not id_re.match(entry.get("id", "")):
            errors.append(f"entry {i} id pattern: {entry.get('id')!r}")
        if not path_re.match(entry.get("path", "")):
            errors.append(f"entry {i} path pattern: {entry.get('path')!r}")
        if not isinstance(entry.get("triggers"), list):
            errors.append(f"entry {i} triggers must be a list")
        body = entry.get("body")
        if body is not None and not isinstance(body, str):
            errors.append(f"entry {i} body must be str or null")
    return errors


def test_generated_source_validates_against_schema() -> None:
    pack = json.loads(_REAL_SOURCE.read_text(encoding="utf-8"))
    schema = json.loads(_REAL_SCHEMA.read_text(encoding="utf-8"))
    errors = _validate_patterns_source(pack, schema)
    assert errors == [], f"schema validation errors: {errors}"


def test_real_pack_exactly_one_proof_body() -> None:
    pack = json.loads(_REAL_SOURCE.read_text(encoding="utf-8"))
    bodied = [p for p in pack["patterns"] if p["body"] is not None]
    assert [p["path"] for p in bodied] == [_PROOF_PATTERN]


def test_schema_display_and_registry() -> None:
    schema = json.loads(_REAL_SCHEMA.read_text(encoding="utf-8"))
    assert schema["x-display"]["heading"] == "id"
    assert schema["x-display"]["body"] is None
    assert set(schema["x-sliceRegistry"]) == {"by-trigger", "list"}
    assert schema["x-sliceRegistry"]["by-trigger"]["filters"] == ["trigger"]
